version: "3.3"
services:
  redis:
    hostname: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
  webapp:
    build:
      context: .
      dockerfile: dockerfile
    image: golang:1.16
    container_name: golang
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: go run app.go